version: '3.3'

services:
  backend:
    build: ./attention_backend
    networks:
      - app-network
    ports:
      - "8000:8000"

  frontend:
    build: ./attention_frontend
    ports:
      - "80:3000"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge