version: '3.8'

services:
  backend:
    build: ./attention_backend
    networks:
      - app-network
    ports:
      - "8000:8000"

  frontend:
    build: ./atention
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge